package com.jtrent238.epicproportions.worldgen.structures;

import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;

public class structureHouseOfEpicProportions { 
	public void spawn(){
}


	public static void spawn(World world, int x, int y, int z) {

		world.setBlock(x+0, y+0, z+0, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+0, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+0, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+0, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+0, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+0, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+0, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+9, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+10, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+11, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+12, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+13, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+14, y+0, z+0, Block.getBlockById(3));
		world.setBlock(x+0, y+0, z+1, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+1, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+1, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+1, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+1, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+1, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+1, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+1, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+0, z+1, 2, 2);
		world.setBlock(x+9, y+0, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+0, z+1, 2, 2);
		world.setBlock(x+10, y+0, z+1, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+10, y+0, z+1, 6, 6);
		world.setBlock(x+11, y+0, z+1, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+11, y+0, z+1, 6, 6);
		world.setBlock(x+12, y+0, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+0, z+1, 2, 2);
		world.setBlock(x+13, y+0, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+0, z+1, 2, 2);
		world.setBlock(x+14, y+0, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+0, z+1, 2, 2);
		world.setBlock(x+0, y+0, z+2, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+2, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+2, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+2, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+2, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+2, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+2, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+2, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+0, z+2, 2, 2);
		world.setBlock(x+9, y+0, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+0, z+2, 2, 2);
		world.setBlock(x+10, y+0, z+2, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+10, y+0, z+2, 6, 6);
		world.setBlock(x+11, y+0, z+2, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+11, y+0, z+2, 6, 6);
		world.setBlock(x+12, y+0, z+2, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+12, y+0, z+2, 6, 6);
		world.setBlock(x+13, y+0, z+2, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+13, y+0, z+2, 6, 6);
		world.setBlock(x+14, y+0, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+0, z+2, 2, 2);
		world.setBlock(x+0, y+0, z+3, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+3, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+3, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+3, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+3, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+3, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+3, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+3, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+0, z+3, 2, 2);
		world.setBlock(x+9, y+0, z+3, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+9, y+0, z+3, 6, 6);
		world.setBlock(x+10, y+0, z+3, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+10, y+0, z+3, 6, 6);
		world.setBlock(x+11, y+0, z+3, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+11, y+0, z+3, 6, 6);
		world.setBlock(x+12, y+0, z+3, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+12, y+0, z+3, 6, 6);
		world.setBlock(x+13, y+0, z+3, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+13, y+0, z+3, 6, 6);
		world.setBlock(x+14, y+0, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+0, z+3, 2, 2);
		world.setBlock(x+0, y+0, z+4, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+4, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+4, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+4, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+4, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+4, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+4, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+4, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+4, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+8, y+0, z+4, 6, 6);
		world.setBlock(x+9, y+0, z+4, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+9, y+0, z+4, 6, 6);
		world.setBlock(x+10, y+0, z+4, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+10, y+0, z+4, 6, 6);
		world.setBlock(x+11, y+0, z+4, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+11, y+0, z+4, 6, 6);
		world.setBlock(x+12, y+0, z+4, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+12, y+0, z+4, 6, 6);
		world.setBlock(x+13, y+0, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+0, z+4, 2, 2);
		world.setBlock(x+14, y+0, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+0, z+4, 2, 2);
		world.setBlock(x+0, y+0, z+5, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+5, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+5, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+5, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+5, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+5, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+5, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+5, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+0, z+5, 2, 2);
		world.setBlock(x+9, y+0, z+5, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+9, y+0, z+5, 6, 6);
		world.setBlock(x+10, y+0, z+5, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+10, y+0, z+5, 6, 6);
		world.setBlock(x+11, y+0, z+5, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+11, y+0, z+5, 6, 6);
		world.setBlock(x+12, y+0, z+5, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+12, y+0, z+5, 6, 6);
		world.setBlock(x+13, y+0, z+5, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+13, y+0, z+5, 6, 6);
		world.setBlock(x+14, y+0, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+0, z+5, 2, 2);
		world.setBlock(x+0, y+0, z+6, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+6, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+6, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+6, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+6, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+6, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+6, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+6, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+0, z+6, 2, 2);
		world.setBlock(x+9, y+0, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+0, z+6, 2, 2);
		world.setBlock(x+10, y+0, z+6, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+10, y+0, z+6, 6, 6);
		world.setBlock(x+11, y+0, z+6, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+11, y+0, z+6, 6, 6);
		world.setBlock(x+12, y+0, z+6, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+12, y+0, z+6, 6, 6);
		world.setBlock(x+13, y+0, z+6, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+13, y+0, z+6, 6, 6);
		world.setBlock(x+14, y+0, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+0, z+6, 2, 2);
		world.setBlock(x+0, y+0, z+7, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+7, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+7, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+7, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+7, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+7, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+7, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+7, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+0, z+7, 2, 2);
		world.setBlock(x+9, y+0, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+0, z+7, 2, 2);
		world.setBlock(x+10, y+0, z+7, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+10, y+0, z+7, 6, 6);
		world.setBlock(x+11, y+0, z+7, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+11, y+0, z+7, 6, 6);
		world.setBlock(x+12, y+0, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+0, z+7, 2, 2);
		world.setBlock(x+13, y+0, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+0, z+7, 2, 2);
		world.setBlock(x+14, y+0, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+0, z+7, 2, 2);
		world.setBlock(x+0, y+0, z+8, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+8, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+8, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+8, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+8, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+8, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+8, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+8, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+8, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+8, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+8, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+8, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+8, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+8, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+8, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+9, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+9, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+9, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+9, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+9, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+9, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+9, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+9, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+9, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+9, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+9, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+9, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+9, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+9, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+9, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+10, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+10, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+10, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+10, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+10, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+10, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+10, Block.getBlockById(3));
		world.setBlock(x+7, y+0, z+10, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+10, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+10, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+10, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+10, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+10, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+10, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+10, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+11, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+11, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+11, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+11, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+11, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+11, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+11, Block.getBlockById(3));
		world.setBlock(x+7, y+0, z+11, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+11, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+11, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+11, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+11, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+11, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+11, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+11, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+12, Block.getBlockById(43));
		world.setBlock(x+1, y+0, z+12, Block.getBlockById(43));
		world.setBlock(x+2, y+0, z+12, Block.getBlockById(43));
		world.setBlock(x+3, y+0, z+12, Block.getBlockById(43));
		world.setBlock(x+4, y+0, z+12, Block.getBlockById(43));
		world.setBlock(x+5, y+0, z+12, Block.getBlockById(43));
		world.setBlock(x+6, y+0, z+12, Block.getBlockById(43));
		world.setBlock(x+7, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+8, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+12, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+13, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+13, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+13, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+13, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+13, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+13, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+13, Block.getBlockById(3));
		world.setBlock(x+7, y+0, z+13, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+13, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+13, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+13, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+13, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+13, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+13, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+13, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+14, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+14, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+14, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+14, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+14, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+14, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+14, Block.getBlockById(3));
		world.setBlock(x+7, y+0, z+14, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+14, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+14, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+14, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+14, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+14, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+14, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+14, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+15, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+15, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+15, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+15, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+15, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+15, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+15, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+15, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+15, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+15, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+15, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+15, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+15, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+15, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+15, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+16, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+16, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+16, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+16, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+16, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+16, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+16, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+16, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+16, Block.getBlockById(5));
		world.setBlock(x+9, y+0, z+16, Block.getBlockById(5));
		world.setBlock(x+10, y+0, z+16, Block.getBlockById(5));
		world.setBlock(x+11, y+0, z+16, Block.getBlockById(5));
		world.setBlock(x+12, y+0, z+16, Block.getBlockById(5));
		world.setBlock(x+13, y+0, z+16, Block.getBlockById(5));
		world.setBlock(x+14, y+0, z+16, Block.getBlockById(5));
		world.setBlock(x+0, y+0, z+17, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+17, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+17, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+17, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+17, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+17, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+17, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+8, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+9, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+10, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+11, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+12, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+13, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+14, y+0, z+17, Block.getBlockById(3));
		world.setBlock(x+0, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+1, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+2, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+3, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+4, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+5, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+6, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+7, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+8, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+9, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+10, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+11, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+12, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+13, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+14, y+0, z+18, Block.getBlockById(2));
		world.setBlock(x+7, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+0, 2, 2);
		world.setBlock(x+8, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+1, z+0, 2, 2);
		world.setBlock(x+9, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+1, z+0, 2, 2);
		world.setBlock(x+10, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+1, z+0, 2, 2);
		world.setBlock(x+11, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+1, z+0, 2, 2);
		world.setBlock(x+12, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+1, z+0, 2, 2);
		world.setBlock(x+13, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+1, z+0, 2, 2);
		world.setBlock(x+14, y+1, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+0, 2, 2);
		world.setBlock(x+6, y+1, z+1, Block.getBlockById(38));
		world.setBlockMetadataWithNotify(x+6, y+1, z+1, 8, 8);
		world.setBlock(x+7, y+1, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+1, 2, 2);
		world.setBlock(x+8, y+1, z+1, Block.getBlockById(54));
		world.setBlockMetadataWithNotify(x+8, y+1, z+1, 5, 5);
		world.setBlock(x+10, y+1, z+1, Block.getBlockById(53));
		world.setBlockMetadataWithNotify(x+10, y+1, z+1, 3, 3);
		world.setBlock(x+11, y+1, z+1, Block.getBlockById(53));
		world.setBlockMetadataWithNotify(x+11, y+1, z+1, 3, 3);
		world.setBlock(x+14, y+1, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+1, 2, 2);
		world.setBlock(x+6, y+1, z+2, Block.getBlockById(38));
		world.setBlockMetadataWithNotify(x+6, y+1, z+2, 8, 8);
		world.setBlock(x+7, y+1, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+2, 2, 2);
		world.setBlock(x+8, y+1, z+2, Block.getBlockById(54));
		world.setBlockMetadataWithNotify(x+8, y+1, z+2, 5, 5);
		world.setBlock(x+14, y+1, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+2, 2, 2);
		world.setBlock(x+6, y+1, z+3, Block.getBlockById(38));
		world.setBlockMetadataWithNotify(x+6, y+1, z+3, 8, 8);
		world.setBlock(x+7, y+1, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+3, 2, 2);
		world.setBlock(x+14, y+1, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+3, 2, 2);
		world.setBlock(x+6, y+1, z+4, Block.getBlockById(38));
		world.setBlockMetadataWithNotify(x+6, y+1, z+4, 8, 8);
		world.setBlock(x+7, y+1, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+4, 2, 2);
		world.setBlock(x+10, y+1, z+4, Block.getBlockById(126));
		world.setBlock(x+11, y+1, z+4, Block.getBlockById(126));
		world.setBlock(x+14, y+1, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+4, 2, 2);
		world.setBlock(x+6, y+1, z+5, Block.getBlockById(38));
		world.setBlockMetadataWithNotify(x+6, y+1, z+5, 8, 8);
		world.setBlock(x+7, y+1, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+5, 2, 2);
		world.setBlock(x+14, y+1, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+5, 2, 2);
		world.setBlock(x+7, y+1, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+6, 2, 2);
		world.setBlock(x+8, y+1, z+6, Block.getBlockById(54));
		world.setBlockMetadataWithNotify(x+8, y+1, z+6, 5, 5);
		world.setBlock(x+14, y+1, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+6, 2, 2);
		world.setBlock(x+7, y+1, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+7, 2, 2);
		world.setBlock(x+8, y+1, z+7, Block.getBlockById(54));
		world.setBlockMetadataWithNotify(x+8, y+1, z+7, 5, 5);
		world.setBlock(x+10, y+1, z+7, Block.getBlockById(53));
		world.setBlockMetadataWithNotify(x+10, y+1, z+7, 2, 2);
		world.setBlock(x+11, y+1, z+7, Block.getBlockById(53));
		world.setBlockMetadataWithNotify(x+11, y+1, z+7, 2, 2);
		world.setBlock(x+14, y+1, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+7, 2, 2);
		world.setBlock(x+7, y+1, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+8, 2, 2);
		world.setBlock(x+8, y+1, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+1, z+8, 2, 2);
		world.setBlock(x+9, y+1, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+1, z+8, 2, 2);
		world.setBlock(x+10, y+1, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+1, z+8, 2, 2);
		world.setBlock(x+11, y+1, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+1, z+8, 2, 2);
		world.setBlock(x+13, y+1, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+1, z+8, 2, 2);
		world.setBlock(x+14, y+1, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+8, 2, 2);
		world.setBlock(x+7, y+1, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+9, 2, 2);
		world.setBlock(x+13, y+1, z+9, Block.getBlockById(61));
		world.setBlockMetadataWithNotify(x+13, y+1, z+9, 4, 4);
		world.setBlock(x+14, y+1, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+9, 2, 2);
		world.setBlock(x+6, y+1, z+10, Block.getBlockById(5));
		world.setBlock(x+7, y+1, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+10, 2, 2);
		world.setBlock(x+13, y+1, z+10, Block.getBlockById(58));
		world.setBlock(x+14, y+1, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+10, 2, 2);
		world.setBlock(x+4, y+1, z+11, Block.getBlockById(144));
		world.setBlockMetadataWithNotify(x+4, y+1, z+11, 1, 1);
		world.setBlock(x+5, y+1, z+11, Block.getBlockById(144));
		world.setBlockMetadataWithNotify(x+5, y+1, z+11, 1, 1);
		world.setBlock(x+6, y+1, z+11, Block.getBlockById(5));
		world.setBlock(x+7, y+1, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+11, 2, 2);
		world.setBlock(x+13, y+1, z+11, Block.getBlockById(54));
		world.setBlockMetadataWithNotify(x+13, y+1, z+11, 4, 4);
		world.setBlock(x+14, y+1, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+11, 2, 2);
		world.setBlock(x+13, y+1, z+12, Block.getBlockById(54));
		world.setBlockMetadataWithNotify(x+13, y+1, z+12, 4, 4);
		world.setBlock(x+14, y+1, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+12, 2, 2);
		world.setBlock(x+4, y+1, z+13, Block.getBlockById(144));
		world.setBlockMetadataWithNotify(x+4, y+1, z+13, 1, 1);
		world.setBlock(x+5, y+1, z+13, Block.getBlockById(144));
		world.setBlockMetadataWithNotify(x+5, y+1, z+13, 1, 1);
		world.setBlock(x+6, y+1, z+13, Block.getBlockById(5));
		world.setBlock(x+7, y+1, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+13, 2, 2);
		world.setBlock(x+14, y+1, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+13, 2, 2);
		world.setBlock(x+6, y+1, z+14, Block.getBlockById(5));
		world.setBlock(x+7, y+1, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+14, 2, 2);
		world.setBlock(x+14, y+1, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+14, 2, 2);
		world.setBlock(x+7, y+1, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+15, 2, 2);
		world.setBlock(x+8, y+1, z+15, Block.getBlockById(26));
		world.setBlockMetadataWithNotify(x+8, y+1, z+15, 9, 9);
		world.setBlock(x+9, y+1, z+15, Block.getBlockById(26));
		world.setBlockMetadataWithNotify(x+9, y+1, z+15, 1, 1);
		world.setBlock(x+14, y+1, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+15, 2, 2);
		world.setBlock(x+7, y+1, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+16, 2, 2);
		world.setBlock(x+8, y+1, z+16, Block.getBlockById(26));
		world.setBlockMetadataWithNotify(x+8, y+1, z+16, 9, 9);
		world.setBlock(x+9, y+1, z+16, Block.getBlockById(26));
		world.setBlockMetadataWithNotify(x+9, y+1, z+16, 1, 1);
		world.setBlock(x+14, y+1, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+16, 2, 2);
		world.setBlock(x+7, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+1, z+17, 2, 2);
		world.setBlock(x+8, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+1, z+17, 2, 2);
		world.setBlock(x+9, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+1, z+17, 2, 2);
		world.setBlock(x+10, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+1, z+17, 2, 2);
		world.setBlock(x+11, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+1, z+17, 2, 2);
		world.setBlock(x+12, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+1, z+17, 2, 2);
		world.setBlock(x+13, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+1, z+17, 2, 2);
		world.setBlock(x+14, y+1, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+1, z+17, 2, 2);
		world.setBlock(x+7, y+2, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+0, 2, 2);
		world.setBlock(x+8, y+2, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+2, z+0, 2, 2);
		world.setBlock(x+9, y+2, z+0, Block.getBlockById(20));
		world.setBlock(x+10, y+2, z+0, Block.getBlockById(20));
		world.setBlock(x+11, y+2, z+0, Block.getBlockById(20));
		world.setBlock(x+12, y+2, z+0, Block.getBlockById(20));
		world.setBlock(x+13, y+2, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+2, z+0, 2, 2);
		world.setBlock(x+14, y+2, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+0, 2, 2);
		world.setBlock(x+6, y+2, z+1, Block.getBlockById(96));
		world.setBlockMetadataWithNotify(x+6, y+2, z+1, 14, 14);
		world.setBlock(x+7, y+2, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+1, 2, 2);
		world.setBlock(x+14, y+2, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+1, 2, 2);
		world.setBlock(x+7, y+2, z+2, Block.getBlockById(20));
		world.setBlock(x+14, y+2, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+2, 2, 2);
		world.setBlock(x+7, y+2, z+3, Block.getBlockById(20));
		world.setBlock(x+14, y+2, z+3, Block.getBlockById(20));
		world.setBlock(x+7, y+2, z+4, Block.getBlockById(20));
		world.setBlock(x+14, y+2, z+4, Block.getBlockById(20));
		world.setBlock(x+6, y+2, z+5, Block.getBlockById(96));
		world.setBlockMetadataWithNotify(x+6, y+2, z+5, 6, 6);
		world.setBlock(x+7, y+2, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+5, 2, 2);
		world.setBlock(x+14, y+2, z+5, Block.getBlockById(20));
		world.setBlock(x+7, y+2, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+6, 2, 2);
		world.setBlock(x+14, y+2, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+6, 2, 2);
		world.setBlock(x+7, y+2, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+7, 2, 2);
		world.setBlock(x+14, y+2, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+7, 2, 2);
		world.setBlock(x+7, y+2, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+8, 2, 2);
		world.setBlock(x+8, y+2, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+2, z+8, 2, 2);
		world.setBlock(x+9, y+2, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+2, z+8, 2, 2);
		world.setBlock(x+10, y+2, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+2, z+8, 2, 2);
		world.setBlock(x+11, y+2, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+2, z+8, 2, 2);
		world.setBlock(x+13, y+2, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+2, z+8, 2, 2);
		world.setBlock(x+14, y+2, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+8, 2, 2);
		world.setBlock(x+7, y+2, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+9, 2, 2);
		world.setBlock(x+14, y+2, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+9, 2, 2);
		world.setBlock(x+7, y+2, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+10, 2, 2);
		world.setBlock(x+14, y+2, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+10, 2, 2);
		world.setBlock(x+6, y+2, z+11, Block.getBlockById(5));
		world.setBlock(x+7, y+2, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+11, 2, 2);
		world.setBlock(x+14, y+2, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+11, 2, 2);
		world.setBlock(x+14, y+2, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+12, 2, 2);
		world.setBlock(x+6, y+2, z+13, Block.getBlockById(5));
		world.setBlock(x+7, y+2, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+13, 2, 2);
		world.setBlock(x+14, y+2, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+13, 2, 2);
		world.setBlock(x+7, y+2, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+14, 2, 2);
		world.setBlock(x+14, y+2, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+14, 2, 2);
		world.setBlock(x+7, y+2, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+15, 2, 2);
		world.setBlock(x+14, y+2, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+15, 2, 2);
		world.setBlock(x+7, y+2, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+16, 2, 2);
		world.setBlock(x+14, y+2, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+16, 2, 2);
		world.setBlock(x+7, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+2, z+17, 2, 2);
		world.setBlock(x+8, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+2, z+17, 2, 2);
		world.setBlock(x+9, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+2, z+17, 2, 2);
		world.setBlock(x+10, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+2, z+17, 2, 2);
		world.setBlock(x+11, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+2, z+17, 2, 2);
		world.setBlock(x+12, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+2, z+17, 2, 2);
		world.setBlock(x+13, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+2, z+17, 2, 2);
		world.setBlock(x+14, y+2, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+2, z+17, 2, 2);
		world.setBlock(x+7, y+3, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+0, 2, 2);
		world.setBlock(x+8, y+3, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+3, z+0, 2, 2);
		world.setBlock(x+9, y+3, z+0, Block.getBlockById(20));
		world.setBlock(x+10, y+3, z+0, Block.getBlockById(20));
		world.setBlock(x+11, y+3, z+0, Block.getBlockById(20));
		world.setBlock(x+12, y+3, z+0, Block.getBlockById(20));
		world.setBlock(x+13, y+3, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+3, z+0, 2, 2);
		world.setBlock(x+14, y+3, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+0, 2, 2);
		world.setBlock(x+6, y+3, z+1, Block.getBlockById(96));
		world.setBlockMetadataWithNotify(x+6, y+3, z+1, 6, 6);
		world.setBlock(x+7, y+3, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+1, 2, 2);
		world.setBlock(x+14, y+3, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+1, 2, 2);
		world.setBlock(x+7, y+3, z+2, Block.getBlockById(20));
		world.setBlock(x+14, y+3, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+2, 2, 2);
		world.setBlock(x+7, y+3, z+3, Block.getBlockById(20));
		world.setBlock(x+14, y+3, z+3, Block.getBlockById(20));
		world.setBlock(x+7, y+3, z+4, Block.getBlockById(20));
		world.setBlock(x+14, y+3, z+4, Block.getBlockById(20));
		world.setBlock(x+6, y+3, z+5, Block.getBlockById(96));
		world.setBlockMetadataWithNotify(x+6, y+3, z+5, 6, 6);
		world.setBlock(x+7, y+3, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+5, 2, 2);
		world.setBlock(x+14, y+3, z+5, Block.getBlockById(20));
		world.setBlock(x+7, y+3, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+6, 2, 2);
		world.setBlock(x+14, y+3, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+6, 2, 2);
		world.setBlock(x+6, y+3, z+7, Block.getBlockById(5));
		world.setBlock(x+7, y+3, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+7, 2, 2);
		world.setBlock(x+14, y+3, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+7, 2, 2);
		world.setBlock(x+6, y+3, z+8, Block.getBlockById(5));
		world.setBlock(x+7, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+8, 2, 2);
		world.setBlock(x+8, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+3, z+8, 2, 2);
		world.setBlock(x+9, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+3, z+8, 2, 2);
		world.setBlock(x+10, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+3, z+8, 2, 2);
		world.setBlock(x+11, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+3, z+8, 2, 2);
		world.setBlock(x+12, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+3, z+8, 2, 2);
		world.setBlock(x+13, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+3, z+8, 2, 2);
		world.setBlock(x+14, y+3, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+8, 2, 2);
		world.setBlock(x+7, y+3, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+9, 2, 2);
		world.setBlock(x+14, y+3, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+9, 2, 2);
		world.setBlock(x+7, y+3, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+10, 2, 2);
		world.setBlock(x+14, y+3, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+10, 2, 2);
		world.setBlock(x+6, y+3, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+6, y+3, z+11, 2, 2);
		world.setBlock(x+7, y+3, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+11, 2, 2);
		world.setBlock(x+8, y+3, z+11, Block.getBlockById(50));
		world.setBlockMetadataWithNotify(x+8, y+3, z+11, 1, 1);
		world.setBlock(x+14, y+3, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+11, 2, 2);
		world.setBlock(x+6, y+3, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+6, y+3, z+12, 2, 2);
		world.setBlock(x+7, y+3, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+12, 2, 2);
		world.setBlock(x+14, y+3, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+12, 2, 2);
		world.setBlock(x+6, y+3, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+6, y+3, z+13, 2, 2);
		world.setBlock(x+7, y+3, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+13, 2, 2);
		world.setBlock(x+8, y+3, z+13, Block.getBlockById(50));
		world.setBlockMetadataWithNotify(x+8, y+3, z+13, 1, 1);
		world.setBlock(x+14, y+3, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+13, 2, 2);
		world.setBlock(x+7, y+3, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+14, 2, 2);
		world.setBlock(x+14, y+3, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+14, 2, 2);
		world.setBlock(x+7, y+3, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+15, 2, 2);
		world.setBlock(x+14, y+3, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+15, 2, 2);
		world.setBlock(x+6, y+3, z+16, Block.getBlockById(5));
		world.setBlock(x+7, y+3, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+16, 2, 2);
		world.setBlock(x+14, y+3, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+16, 2, 2);
		world.setBlock(x+6, y+3, z+17, Block.getBlockById(5));
		world.setBlock(x+7, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+3, z+17, 2, 2);
		world.setBlock(x+8, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+3, z+17, 2, 2);
		world.setBlock(x+9, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+3, z+17, 2, 2);
		world.setBlock(x+10, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+3, z+17, 2, 2);
		world.setBlock(x+11, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+3, z+17, 2, 2);
		world.setBlock(x+12, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+3, z+17, 2, 2);
		world.setBlock(x+13, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+3, z+17, 2, 2);
		world.setBlock(x+14, y+3, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+3, z+17, 2, 2);
		world.setBlock(x+7, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+0, 2, 2);
		world.setBlock(x+8, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+4, z+0, 2, 2);
		world.setBlock(x+9, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+4, z+0, 2, 2);
		world.setBlock(x+10, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+4, z+0, 2, 2);
		world.setBlock(x+11, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+4, z+0, 2, 2);
		world.setBlock(x+12, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+4, z+0, 2, 2);
		world.setBlock(x+13, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+4, z+0, 2, 2);
		world.setBlock(x+14, y+4, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+0, 2, 2);
		world.setBlock(x+7, y+4, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+1, 2, 2);
		world.setBlock(x+8, y+4, z+1, Block.getBlockById(50));
		world.setBlockMetadataWithNotify(x+8, y+4, z+1, 1, 1);
		world.setBlock(x+13, y+4, z+1, Block.getBlockById(50));
		world.setBlockMetadataWithNotify(x+13, y+4, z+1, 2, 2);
		world.setBlock(x+14, y+4, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+1, 2, 2);
		world.setBlock(x+7, y+4, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+2, 2, 2);
		world.setBlock(x+14, y+4, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+2, 2, 2);
		world.setBlock(x+7, y+4, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+3, 2, 2);
		world.setBlock(x+14, y+4, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+3, 2, 2);
		world.setBlock(x+7, y+4, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+4, 2, 2);
		world.setBlock(x+14, y+4, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+4, 2, 2);
		world.setBlock(x+7, y+4, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+5, 2, 2);
		world.setBlock(x+14, y+4, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+5, 2, 2);
		world.setBlock(x+7, y+4, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+6, 2, 2);
		world.setBlock(x+14, y+4, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+6, 2, 2);
		world.setBlock(x+7, y+4, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+7, 2, 2);
		world.setBlock(x+8, y+4, z+7, Block.getBlockById(50));
		world.setBlockMetadataWithNotify(x+8, y+4, z+7, 1, 1);
		world.setBlock(x+13, y+4, z+7, Block.getBlockById(50));
		world.setBlockMetadataWithNotify(x+13, y+4, z+7, 2, 2);
		world.setBlock(x+14, y+4, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+7, 2, 2);
		world.setBlock(x+6, y+4, z+8, Block.getBlockById(5));
		world.setBlock(x+7, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+8, 2, 2);
		world.setBlock(x+8, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+4, z+8, 2, 2);
		world.setBlock(x+9, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+4, z+8, 2, 2);
		world.setBlock(x+10, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+4, z+8, 2, 2);
		world.setBlock(x+11, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+4, z+8, 2, 2);
		world.setBlock(x+12, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+4, z+8, 2, 2);
		world.setBlock(x+13, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+4, z+8, 2, 2);
		world.setBlock(x+14, y+4, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+8, 2, 2);
		world.setBlock(x+6, y+4, z+9, Block.getBlockById(5));
		world.setBlock(x+7, y+4, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+9, 2, 2);
		world.setBlock(x+14, y+4, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+9, 2, 2);
		world.setBlock(x+7, y+4, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+10, 2, 2);
		world.setBlock(x+14, y+4, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+10, 2, 2);
		world.setBlock(x+6, y+4, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+6, y+4, z+11, 2, 2);
		world.setBlock(x+7, y+4, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+11, 2, 2);
		world.setBlock(x+14, y+4, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+11, 2, 2);
		world.setBlock(x+6, y+4, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+6, y+4, z+12, 2, 2);
		world.setBlock(x+7, y+4, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+12, 2, 2);
		world.setBlock(x+14, y+4, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+12, 2, 2);
		world.setBlock(x+6, y+4, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+6, y+4, z+13, 2, 2);
		world.setBlock(x+7, y+4, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+13, 2, 2);
		world.setBlock(x+14, y+4, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+13, 2, 2);
		world.setBlock(x+7, y+4, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+14, 2, 2);
		world.setBlock(x+14, y+4, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+14, 2, 2);
		world.setBlock(x+6, y+4, z+15, Block.getBlockById(5));
		world.setBlock(x+7, y+4, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+15, 2, 2);
		world.setBlock(x+14, y+4, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+15, 2, 2);
		world.setBlock(x+6, y+4, z+16, Block.getBlockById(5));
		world.setBlock(x+7, y+4, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+16, 2, 2);
		world.setBlock(x+14, y+4, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+16, 2, 2);
		world.setBlock(x+7, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+4, z+17, 2, 2);
		world.setBlock(x+8, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+4, z+17, 2, 2);
		world.setBlock(x+9, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+4, z+17, 2, 2);
		world.setBlock(x+10, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+4, z+17, 2, 2);
		world.setBlock(x+11, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+4, z+17, 2, 2);
		world.setBlock(x+12, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+4, z+17, 2, 2);
		world.setBlock(x+13, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+4, z+17, 2, 2);
		world.setBlock(x+14, y+4, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+4, z+17, 2, 2);
		world.setBlock(x+7, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+0, 2, 2);
		world.setBlock(x+8, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+0, 2, 2);
		world.setBlock(x+9, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+0, 2, 2);
		world.setBlock(x+10, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+0, 2, 2);
		world.setBlock(x+11, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+0, 2, 2);
		world.setBlock(x+12, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+0, 2, 2);
		world.setBlock(x+13, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+0, 2, 2);
		world.setBlock(x+14, y+5, z+0, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+0, 2, 2);
		world.setBlock(x+7, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+1, 2, 2);
		world.setBlock(x+8, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+1, 2, 2);
		world.setBlock(x+9, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+1, 2, 2);
		world.setBlock(x+10, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+1, 2, 2);
		world.setBlock(x+11, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+1, 2, 2);
		world.setBlock(x+12, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+1, 2, 2);
		world.setBlock(x+13, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+1, 2, 2);
		world.setBlock(x+14, y+5, z+1, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+1, 2, 2);
		world.setBlock(x+7, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+2, 2, 2);
		world.setBlock(x+8, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+2, 2, 2);
		world.setBlock(x+9, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+2, 2, 2);
		world.setBlock(x+10, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+2, 2, 2);
		world.setBlock(x+11, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+2, 2, 2);
		world.setBlock(x+12, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+2, 2, 2);
		world.setBlock(x+13, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+2, 2, 2);
		world.setBlock(x+14, y+5, z+2, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+2, 2, 2);
		world.setBlock(x+7, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+3, 2, 2);
		world.setBlock(x+8, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+3, 2, 2);
		world.setBlock(x+9, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+3, 2, 2);
		world.setBlock(x+10, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+3, 2, 2);
		world.setBlock(x+11, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+3, 2, 2);
		world.setBlock(x+12, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+3, 2, 2);
		world.setBlock(x+13, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+3, 2, 2);
		world.setBlock(x+14, y+5, z+3, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+3, 2, 2);
		world.setBlock(x+7, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+4, 2, 2);
		world.setBlock(x+8, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+4, 2, 2);
		world.setBlock(x+9, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+4, 2, 2);
		world.setBlock(x+10, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+4, 2, 2);
		world.setBlock(x+11, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+4, 2, 2);
		world.setBlock(x+12, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+4, 2, 2);
		world.setBlock(x+13, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+4, 2, 2);
		world.setBlock(x+14, y+5, z+4, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+4, 2, 2);
		world.setBlock(x+7, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+5, 2, 2);
		world.setBlock(x+8, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+5, 2, 2);
		world.setBlock(x+9, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+5, 2, 2);
		world.setBlock(x+10, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+5, 2, 2);
		world.setBlock(x+11, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+5, 2, 2);
		world.setBlock(x+12, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+5, 2, 2);
		world.setBlock(x+13, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+5, 2, 2);
		world.setBlock(x+14, y+5, z+5, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+5, 2, 2);
		world.setBlock(x+7, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+6, 2, 2);
		world.setBlock(x+8, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+6, 2, 2);
		world.setBlock(x+9, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+6, 2, 2);
		world.setBlock(x+10, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+6, 2, 2);
		world.setBlock(x+11, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+6, 2, 2);
		world.setBlock(x+12, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+6, 2, 2);
		world.setBlock(x+13, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+6, 2, 2);
		world.setBlock(x+14, y+5, z+6, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+6, 2, 2);
		world.setBlock(x+7, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+7, 2, 2);
		world.setBlock(x+8, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+7, 2, 2);
		world.setBlock(x+9, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+7, 2, 2);
		world.setBlock(x+10, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+7, 2, 2);
		world.setBlock(x+11, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+7, 2, 2);
		world.setBlock(x+12, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+7, 2, 2);
		world.setBlock(x+13, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+7, 2, 2);
		world.setBlock(x+14, y+5, z+7, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+7, 2, 2);
		world.setBlock(x+7, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+8, 2, 2);
		world.setBlock(x+8, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+8, 2, 2);
		world.setBlock(x+9, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+8, 2, 2);
		world.setBlock(x+10, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+8, 2, 2);
		world.setBlock(x+11, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+8, 2, 2);
		world.setBlock(x+12, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+8, 2, 2);
		world.setBlock(x+13, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+8, 2, 2);
		world.setBlock(x+14, y+5, z+8, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+8, 2, 2);
		world.setBlock(x+6, y+5, z+9, Block.getBlockById(5));
		world.setBlock(x+7, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+9, 2, 2);
		world.setBlock(x+8, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+9, 2, 2);
		world.setBlock(x+9, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+9, 2, 2);
		world.setBlock(x+10, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+9, 2, 2);
		world.setBlock(x+11, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+9, 2, 2);
		world.setBlock(x+12, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+9, 2, 2);
		world.setBlock(x+13, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+9, 2, 2);
		world.setBlock(x+14, y+5, z+9, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+9, 2, 2);
		world.setBlock(x+6, y+5, z+10, Block.getBlockById(5));
		world.setBlock(x+7, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+10, 2, 2);
		world.setBlock(x+8, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+10, 2, 2);
		world.setBlock(x+9, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+10, 2, 2);
		world.setBlock(x+10, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+10, 2, 2);
		world.setBlock(x+11, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+10, 2, 2);
		world.setBlock(x+12, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+10, 2, 2);
		world.setBlock(x+13, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+10, 2, 2);
		world.setBlock(x+14, y+5, z+10, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+10, 2, 2);
		world.setBlock(x+6, y+5, z+11, Block.getBlockById(5));
		world.setBlock(x+7, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+11, 2, 2);
		world.setBlock(x+8, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+11, 2, 2);
		world.setBlock(x+9, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+11, 2, 2);
		world.setBlock(x+10, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+11, 2, 2);
		world.setBlock(x+11, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+11, 2, 2);
		world.setBlock(x+12, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+11, 2, 2);
		world.setBlock(x+13, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+11, 2, 2);
		world.setBlock(x+14, y+5, z+11, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+11, 2, 2);
		world.setBlock(x+6, y+5, z+12, Block.getBlockById(5));
		world.setBlock(x+7, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+12, 2, 2);
		world.setBlock(x+8, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+12, 2, 2);
		world.setBlock(x+9, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+12, 2, 2);
		world.setBlock(x+10, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+12, 2, 2);
		world.setBlock(x+11, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+12, 2, 2);
		world.setBlock(x+12, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+12, 2, 2);
		world.setBlock(x+13, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+12, 2, 2);
		world.setBlock(x+14, y+5, z+12, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+12, 2, 2);
		world.setBlock(x+6, y+5, z+13, Block.getBlockById(5));
		world.setBlock(x+7, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+13, 2, 2);
		world.setBlock(x+8, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+13, 2, 2);
		world.setBlock(x+9, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+13, 2, 2);
		world.setBlock(x+10, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+13, 2, 2);
		world.setBlock(x+11, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+13, 2, 2);
		world.setBlock(x+12, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+13, 2, 2);
		world.setBlock(x+13, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+13, 2, 2);
		world.setBlock(x+14, y+5, z+13, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+13, 2, 2);
		world.setBlock(x+6, y+5, z+14, Block.getBlockById(5));
		world.setBlock(x+7, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+14, 2, 2);
		world.setBlock(x+8, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+14, 2, 2);
		world.setBlock(x+9, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+14, 2, 2);
		world.setBlock(x+10, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+14, 2, 2);
		world.setBlock(x+11, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+14, 2, 2);
		world.setBlock(x+12, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+14, 2, 2);
		world.setBlock(x+13, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+14, 2, 2);
		world.setBlock(x+14, y+5, z+14, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+14, 2, 2);
		world.setBlock(x+6, y+5, z+15, Block.getBlockById(5));
		world.setBlock(x+7, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+15, 2, 2);
		world.setBlock(x+8, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+15, 2, 2);
		world.setBlock(x+9, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+15, 2, 2);
		world.setBlock(x+10, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+15, 2, 2);
		world.setBlock(x+11, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+15, 2, 2);
		world.setBlock(x+12, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+15, 2, 2);
		world.setBlock(x+13, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+15, 2, 2);
		world.setBlock(x+14, y+5, z+15, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+15, 2, 2);
		world.setBlock(x+7, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+16, 2, 2);
		world.setBlock(x+8, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+16, 2, 2);
		world.setBlock(x+9, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+16, 2, 2);
		world.setBlock(x+10, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+16, 2, 2);
		world.setBlock(x+11, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+16, 2, 2);
		world.setBlock(x+12, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+16, 2, 2);
		world.setBlock(x+13, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+16, 2, 2);
		world.setBlock(x+14, y+5, z+16, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+16, 2, 2);
		world.setBlock(x+7, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+7, y+5, z+17, 2, 2);
		world.setBlock(x+8, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+8, y+5, z+17, 2, 2);
		world.setBlock(x+9, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+9, y+5, z+17, 2, 2);
		world.setBlock(x+10, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+10, y+5, z+17, 2, 2);
		world.setBlock(x+11, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+11, y+5, z+17, 2, 2);
		world.setBlock(x+12, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+12, y+5, z+17, 2, 2);
		world.setBlock(x+13, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+13, y+5, z+17, 2, 2);
		world.setBlock(x+14, y+5, z+17, Block.getBlockById(5));
		world.setBlockMetadataWithNotify(x+14, y+5, z+17, 2, 2);
		world.setBlock(x+6, y+6, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+6, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+6, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+7, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+7, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+7, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+8, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+8, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+8, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+9, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+9, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+9, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+10, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+10, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+10, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+11, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+11, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+11, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+12, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+12, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+12, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+13, z+11, Block.getBlockById(46));
		world.setBlock(x+6, y+13, z+12, Block.getBlockById(46));
		world.setBlock(x+6, y+13, z+13, Block.getBlockById(46));
		world.setBlock(x+6, y+14, z+12, Block.getBlockById(46));
		world.setBlock(x+14, y+16, z+0, Block.getBlockById(35));
		world.setBlockMetadataWithNotify(x+14, y+16, z+0, 10, 10);
	}
}