Block.defineBlock(215, "blockFlowerChocolate", [[blockFlowerChocolate],[blockFlowerChocolate],[blockFlowerChocolate],[blockFlowerChocolate],[blockFlowerChocolate],[blockFlowerChocolate]]);
Item.setCategory(215, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(215);
Block.defineBlock(214, "blockFlowerLove", [[blockFlowerLove],[blockFlowerLove],[blockFlowerLove],[blockFlowerLove],[blockFlowerLove],[blockFlowerLove]]);
Item.setCategory(214, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(214);
Block.defineBlock(213, "blockFlowerRainbow", [[blockFlowerRainbow],[blockFlowerRainbow],[blockFlowerRainbow],[blockFlowerRainbow],[blockFlowerRainbow],[blockFlowerRainbow]]);
Item.setCategory(213, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(213);
Block.defineBlock(212, "blockFlowerPinkHeart", [[blockFlowerPinkHeart],[blockFlowerPinkHeart],[blockFlowerPinkHeart],[blockFlowerPinkHeart],[blockFlowerPinkHeart],[blockFlowerPinkHeart]]);
Item.setCategory(212, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(212);
Block.defineBlock(211, "blockFlowerRedHeart", [[blockFlowerRedHeart],[blockFlowerRedHeart],[blockFlowerRedHeart],[blockFlowerRedHeart],[blockFlowerRedHeart],[blockFlowerRedHeart]]);
Item.setCategory(211, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(211);
Block.defineBlock(210, "blockFlowerForJen", [[blockFlowerForJen],[blockFlowerForJen],[blockFlowerForJen],[blockFlowerForJen],[blockFlowerForJen],[blockFlowerForJen]]);
Item.setCategory(210, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(210);
Block.defineBlock(209, "blockTrollTNT", [[blockTrollTNT_bottom],[blockTrollTNT_top],[blockTrollTNT_side],[blockTrollTNT_side],[blockTrollTNT_side],[blockTrollTNT_side]]);
Item.setCategory(209, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(209);
Block.defineBlock(208, "blockJenChest", [[blockJenChest],[blockJenChest],[blockJenChest],[blockJenChest],[blockJenChest],[blockJenChest]]);
Item.setCategory(208, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(208);
Block.defineBlock(207, "blockPatChest", [[blockPatChest],[blockPatChest],[blockPatChest],[blockPatChest],[blockPatChest],[blockPatChest]]);
Item.setCategory(207, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(207);
Block.defineBlock(206, "blockBirthdayPresent", [[blockBirthdayPresent_bottom],[blockBirthdayPresent_top],[blockBirthdayPresent_side],[blockBirthdayPresent_side],[blockBirthdayPresent_side],[blockBirthdayPresent_side]]);
Item.setCategory(206, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(206);
Block.defineBlock(205, "blockPatTNT", [[blockPatTNT_bottom],[blockPatTNT_top],[blockPatTNT_side],[blockPatTNT_side],[blockPatTNT_side],[blockPatTNT_side]]);
Item.setCategory(205, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(205);
Block.defineBlock(204, "blockJenOre", [[blockJenOre],[blockJenOre],[blockJenOre],[blockJenOre],[blockJenOre],[blockJenOre]]);
Item.setCategory(204, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(204);
Block.defineBlock(203, "blockPatOre", [[blockPatOre],[blockPatOre],[blockPatOre],[blockPatOre],[blockPatOre],[blockPatOre]]);
Item.setCategory(203, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(203);
Block.defineBlock(202, "blockJenIngot", [[blockJenIngot],[blockJenIngot],[blockJenIngot],[blockJenIngot],[blockJenIngot],[blockJenIngot]]);
Item.setCategory(202, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(202);
Block.defineBlock(201, "blockPatIngot", [[blockPatIngot],[blockPatIngot],[blockPatIngot],[blockPatIngot],[blockPatIngot],[blockPatIngot]]);
Item.setCategory(201, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(201);
Block.defineBlock(200, "blockFartBomb", [[blockFartBomb_bottom],[blockFartBomb_top],[blockFartBomb_side],[blockFartBomb_side],[blockFartBomb_side],[blockFartBomb_side]]);
Item.setCategory(200, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(200);
ModPE.setItem(1113, itemSpawnJenVillager, "itemSpawnJenVillager");
Item.setCategory(1113, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1113);
ModPE.setItem(1112, itemSpawnPatVillager, "itemSpawnPatVillager");
Item.setCategory(1112, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1112);
ModPE.setItem(1111, itemSpawnVillagerOfEpicProportions, "itemSpawnVillagerOfEpicProportions");
Item.setCategory(1111, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1111);
ModPE.setItem(1110, itemSpawnBlockling, "itemSpawnBlockling");
Item.setCategory(1110, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1110);
ModPE.setItem(1109, itemSpawnBanana, "itemSpawnBanana");
Item.setCategory(1109, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1109);
ModPE.setItem(1108, itemSpawnPopo, "itemSpawnPopo");
Item.setCategory(1108, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1108);
ModPE.setItem(1107, itemSpawnKami, "itemSpawnKami");
Item.setCategory(1107, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1107);
ModPE.setItem(1106, itemSpawnKitty, "itemSpawnKitty");
Item.setCategory(1106, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1106);
ModPE.setItem(1105, itemSpawnSparky, "itemSpawnSparky");
Item.setCategory(1105, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1105);
ModPE.setItem(1104, itemSpawnCandyPopper, "itemSpawnCandyPopper");
Item.setCategory(1104, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1104);
ModPE.setItem(1103, itemSpawnClown, "itemSpawnClown");
Item.setCategory(1103, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1103);
ModPE.setItem(1102, itemSpawnjtrent238, "itemSpawnjtrent238");
Item.setCategory(1102, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1102);
ModPE.setItem(1101, itemSpawnCookieLittle, "itemSpawnCookieLittle");
Item.setCategory(1101, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1101);
ModPE.setItem(1100, itemSpawnCandyMan, "itemSpawnCandyMan");
Item.setCategory(1100, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1100);
ModPE.setItem(1099, itemSpawnNinjaMaster, "itemSpawnNinjaMaster");
Item.setCategory(1099, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1099);
ModPE.setItem(1098, itemSpawnFred2_0, "itemSpawnFred2_0");
Item.setCategory(1098, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1098);
ModPE.setItem(1097, itemSpawnJen, "itemSpawnJen");
Item.setCategory(1097, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1097);
ModPE.setItem(1096, itemSpawnPat, "itemSpawnPat");
Item.setCategory(1096, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1096);
ModPE.setItem(1095, itemSpawnCaptianCookie, "itemSpawnCaptianCookie");
Item.setCategory(1095, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1095);
ModPE.setItem(1094, itemSpawnBomby, "itemSpawnBomby");
Item.setCategory(1094, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1094);
ModPE.setItem(1093, itemSuperJenBoots, "itemSuperJenBoots");
Item.setCategory(1093, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1093);
ModPE.setItem(1092, itemSuperJenLeggings, "itemSuperJenLeggings");
Item.setCategory(1092, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1092);
ModPE.setItem(1091, itemSuperJenChestplate, "itemSuperJenChestplate");
Item.setCategory(1091, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1091);
ModPE.setItem(1090, itemSuperJenHelmet, "itemSuperJenHelmet");
Item.setCategory(1090, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1090);
ModPE.setItem(1089, itemSuperPatBoots, "itemSuperPatBoots");
Item.setCategory(1089, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1089);
ModPE.setItem(1088, itemSuperPatLeggings, "itemSuperPatLeggings");
Item.setCategory(1088, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1088);
ModPE.setItem(1087, itemSuperPatChestplate, "itemSuperPatChestplate");
Item.setCategory(1087, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1087);
ModPE.setItem(1086, itemSuperPatHelmet, "itemSuperPatHelmet");
Item.setCategory(1086, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1086);
ModPE.setItem(1085, itemJenBoots, "itemJenBoots");
Item.setCategory(1085, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1085);
ModPE.setItem(1084, itemJenLeggings, "itemJenLeggings");
Item.setCategory(1084, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1084);
ModPE.setItem(1083, itemJenChestplate, "itemJenChestplate");
Item.setCategory(1083, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1083);
ModPE.setItem(1082, itemJenHelmet, "itemJenHelmet");
Item.setCategory(1082, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1082);
ModPE.setItem(1081, itemPatBoots, "itemPatBoots");
Item.setCategory(1081, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1081);
ModPE.setItem(1080, itemPatLeggings, "itemPatLeggings");
Item.setCategory(1080, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1080);
ModPE.setItem(1079, itemPatChestplate, "itemPatChestplate");
Item.setCategory(1079, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1079);
ModPE.setItem(1078, itemPatHelmet, "itemPatHelmet");
Item.setCategory(1078, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1078);
ModPE.setItem(1077, itemAxeOfEpicProportions, "itemAxeOfEpicProportions");
Item.setCategory(1077, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1077);
ModPE.setItem(1076, itemHoeOfEpicProportions, "itemHoeOfEpicProportions");
Item.setCategory(1076, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1076);
ModPE.setItem(1075, itemShovelOfEpicProportions, "itemShovelOfEpicProportions");
Item.setCategory(1075, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1075);
ModPE.setItem(1074, itemPickOfEpicProportions, "itemPickOfEpicProportions");
Item.setCategory(1074, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1074);
ModPE.setItem(1073, itemSwordOfEpicProportions, "itemSwordOfEpicProportions");
Item.setCategory(1073, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1073);
ModPE.setItem(1072, itemSuperJenMultiTool, "itemSuperJenMultiTool");
Item.setCategory(1072, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1072);
ModPE.setItem(1071, itemSuperPatMultiTool, "itemSuperPatMultiTool");
Item.setCategory(1071, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1071);
ModPE.setItem(1070, itemSuperJenHoe, "itemSuperJenHoe");
Item.setCategory(1070, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1070);
ModPE.setItem(1069, itemSuperPatHoe, "itemSuperPatHoe");
Item.setCategory(1069, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1069);
ModPE.setItem(1068, itemSuperJenShovel, "itemSuperJenShovel");
Item.setCategory(1068, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1068);
ModPE.setItem(1067, itemSuperPatShovel, "itemSuperPatShovel");
Item.setCategory(1067, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1067);
ModPE.setItem(1067, itemSuperPatShovel, "itemSuperPatShovel");
Item.setCategory(1067, ItemCategory.);
Player.addItemCreativeInv(1067);
ModPE.setItem(1066, itemSuperJenAxe, "itemSuperJenAxe");
Item.setCategory(1066, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1066);
ModPE.setItem(1065, itemSuperPatAxe, "itemSuperPatAxe");
Item.setCategory(1065, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1065);
ModPE.setItem(1064, itemSuperJenPick, "itemSuperJenPick");
Item.setCategory(1064, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1064);
ModPE.setItem(1063, itemSuperPatPick, "itemSuperPatPick");
Item.setCategory(1063, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1063);
ModPE.setItem(1062, itemSuperJenSword, "itemSuperJenSword");
Item.setCategory(1062, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1062);
ModPE.setItem(1061, itemSuperPatSword, "itemSuperPatSword");
Item.setCategory(1061, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1061);
ModPE.setItem(1060, itemJenMultiTool, "itemJenMultiTool");
Item.setCategory(1060, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1060);
ModPE.setItem(1059, itemPatMultiTool, "itemPatMultiTool");
Item.setCategory(1059, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1059);
ModPE.setItem(1058, itemJenArrow, "itemJenArrow");
Item.setCategory(1058, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1058);
ModPE.setItem(1057, itemPatArrow, "itemPatArrow");
Item.setCategory(1057, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1057);
ModPE.setItem(1056, itemJenBow, "itemJenBow");
Item.setCategory(1056, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1056);
ModPE.setItem(1055, itemPatBow, "itemPatBow");
Item.setCategory(1055, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1055);
ModPE.setItem(1054, itemJenStaff, "itemJenStaff");
Item.setCategory(1054, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1054);
ModPE.setItem(1053, itemPatStaff, "itemPatStaff");
Item.setCategory(1053, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1053);
ModPE.setItem(1052, itemJenHoe, "itemJenHoe");
Item.setCategory(1052, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1052);
ModPE.setItem(1051, itemPatHoe, "itemPatHoe");
Item.setCategory(1051, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1051);
ModPE.setItem(1050, itemJenShovel, "itemJenShovel");
Item.setCategory(1050, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1050);
ModPE.setItem(1049, itemPatShovel, "itemPatShovel");
Item.setCategory(1049, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1049);
ModPE.setItem(1048, itemJenAxe, "itemJenAxe");
Item.setCategory(1048, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1048);
ModPE.setItem(1047, itemPatAxe, "itemPatAxe");
Item.setCategory(1047, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1047);
ModPE.setItem(1046, itemJenPick, "itemJenPick");
Item.setCategory(1046, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1046);
ModPE.setItem(1045, itemPatPick, "itemPatPick");
Item.setCategory(1045, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1045);
ModPE.setItem(1044, itemJenSword, "itemJenSword");
Item.setCategory(1044, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1044);
ModPE.setItem(1043, itemPatSword, "itemPatSword");
Item.setCategory(1043, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1043);
ModPE.setItem(1042, itemFartBombLauncher, "itemFartBombLauncher");
Item.setCategory(1042, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1042);
ModPE.setItem(1041, itemTrollTNTLauncher, "itemTrollTNTLauncher");
Item.setCategory(1041, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1041);
ModPE.setItem(1040, itemPatTNTLauncher, "itemPatTNTLauncher");
Item.setCategory(1040, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1040);
ModPE.setItem(1039, itemTNTLauncher, "itemTNTLauncher");
Item.setCategory(1039, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1039);
ModPE.setItem(1038, itemShovelOfEpicProportions_Part3, "itemShovelOfEpicProportions_Part3");
Item.setCategory(1038, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1038);
ModPE.setItem(1037, itemShovelOfEpicProportions_Part2, "itemShovelOfEpicProportions_Part2");
Item.setCategory(1037, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1037);
ModPE.setItem(1036, itemShovelOfEpicProportions_Part1, "itemShovelOfEpicProportions_Part1");
Item.setCategory(1036, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1036);
ModPE.setItem(1035, itemJenGun, "itemJenGun");
Item.setCategory(1035, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1035);
ModPE.setItem(1034, itemPatGun, "itemPatGun");
Item.setCategory(1034, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1034);
ModPE.setItem(1033, itemJenWellPlacer, "itemJenWellPlacer");
Item.setCategory(1033, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1033);
ModPE.setItem(1032, itemPatWellPlacer, "itemPatWellPlacer");
Item.setCategory(1032, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1032);
ModPE.setItem(1031, itemPickOfEpicProportions_Part3, "itemPickOfEpicProportions_Part3");
Item.setCategory(1031, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1031);
ModPE.setItem(1030, itemPickOfEpicProportions_Part2, "itemPickOfEpicProportions_Part2");
Item.setCategory(1030, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1030);
ModPE.setItem(1029, itemPickOfEpicProportions_Part1, "itemPickOfEpicProportions_Part1");
Item.setCategory(1029, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1029);
ModPE.setItem(1028, itemModInfo, "itemModInfo");
Item.setCategory(1028, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1028);
ModPE.setItem(1027, ItemCookedPufferFish, "ItemCookedPufferFish");
Item.setCategory(1027, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1027);
ModPE.setItem(1026, itemJenmeat_cooked, "itemJenmeat_cooked");
Item.setCategory(1026, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1026);
ModPE.setItem(1025, itemJenmeat_raw, "itemJenmeat_raw");
Item.setCategory(1025, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1025);
ModPE.setItem(1024, itemPatmeat_cooked, "itemPatmeat_cooked");
Item.setCategory(1024, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1024);
ModPE.setItem(1023, itemPatmeat_raw, "itemPatmeat_raw");
Item.setCategory(1023, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1023);
ModPE.setItem(1022, itemjenapple, "itemjenapple");
Item.setCategory(1022, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1022);
ModPE.setItem(1021, itempatapple, "itempatapple");
Item.setCategory(1021, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1021);
ModPE.setItem(1020, itemjendoor, "itemjendoor");
Item.setCategory(1020, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1020);
ModPE.setItem(1019, itempatdoor, "itempatdoor");
Item.setCategory(1019, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1019);
ModPE.setItem(1018, itemSwordOfEpicProportions_Part3, "itemSwordOfEpicProportions_Part3");
Item.setCategory(1018, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1018);
ModPE.setItem(1017, itemSwordOfEpicProportions_Part2, "itemSwordOfEpicProportions_Part2");
Item.setCategory(1017, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1017);
ModPE.setItem(1016, itemSwordOfEpicProportions_Part1, "itemSwordOfEpicProportions_Part1");
Item.setCategory(1016, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1016);
ModPE.setItem(1015, itemJensHoleStructurePlacer_5, "itemJensHoleStructurePlacer_5");
Item.setCategory(1015, ItemCategory.itemJensHoleStructurePlacer_5);
Player.addItemCreativeInv(1015);
ModPE.setItem(1014, itemJensHoleStructurePlacer_4, "itemJensHoleStructurePlacer_4");
Item.setCategory(1014, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1014);
ModPE.setItem(1013, itemJensHoleStructurePlacer_3, "itemJensHoleStructurePlacer_3");
Item.setCategory(1013, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1013);
ModPE.setItem(1012, itemJensHoleStructurePlacer_2, "itemJensHoleStructurePlacer_2");
Item.setCategory(1012, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1012);
ModPE.setItem(1011, itemJensHoleStructurePlacer_1, "itemJensHoleStructurePlacer_1");
Item.setCategory(1011, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1011);
ModPE.setItem(1010, itemBombyStructurePlacer, "itemBombyStructurePlacer");
Item.setCategory(1010, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1010);
ModPE.setItem(1009, itemHouseOfEpicProportionsPlacer, "itemHouseOfEpicProportionsPlacer");
Item.setCategory(1009, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1009);
ModPE.setItem(1008, itemBirthdayPresent, "itemBirthdayPresent");
Item.setCategory(1008, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1008);
ModPE.setItem(1007, itemEpicProportionsStar, "itemEpicProportionsStar");
Item.setCategory(1007, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1007);
ModPE.setItem(1006, itemPatStar, "itemPatStar");
Item.setCategory(1006, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1006);
ModPE.setItem(1005, itemJenStar, "itemJenStar");
Item.setCategory(1005, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1005);
ModPE.setItem(1004, itemCaptainCookieCookie, "itemCaptainCookieCookie");
Item.setCategory(1004, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1004);
ModPE.setItem(1003, itemJenslips, "itemJenslips");
Item.setCategory(1003, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1003);
ModPE.setItem(1002, itemJenIngot, "itemJenIngot");
Item.setCategory(1002, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1002);
ModPE.setItem(1001, itemPatIngot, "itemPatIngot");
Item.setCategory(1001, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1001);
ModPE.setItem(1000, itemgemofepicproportions, "itemgemofepicproportions");
Item.setCategory(1000, ItemCategory.EpicProportionsMod);
Player.addItemCreativeInv(1000);
Item.addFurnaceRecipe(202,1002,0);
Item.addFurnaceRecipe(201,1001,0);
Item.addFurnaceRecipe(462,1027,0);
Item.addFurnaceRecipe(1025,1026,0);
Item.addFurnaceRecipe(1023,1024,0);
Item.addCraftRecipe(1043,0,0,[1001,1,0,1001,1,0,280,1,0]);
function newLevel() {
    clientMessage("Welcome player");
}
function leaveGame() {
    print("Goodbye");
}
function entityAddedHook(entity) {
    if (Entity.getEntityTypeId(entity) == 33) {
        clientMessage("Watch out, a creeper has spawned!");
    }
}
function entityRemovedHook(entity) {
    if (Entity.getEntityTypeId(entity) == 81) { 
        clientMessage("A snowball was thrown and has now broke.");
    }
}
function deathHook(murderer, victim) {
    if (Player.getEntity() == murderer) {
        clientMessage("How could you?!");
    }
}
function procCmd(cmd) {
    cmd = cmd.toLowerCase();
    if (cmd == "help"){
        clientMessage("Was this helpful enough?");
    }
}
function attackHook(attacker, victim) {
    if (attacker == Player.getEntity()) {
        clientMessage("Sir, you shouldn't attack others.");
    } else {
        clientMessage("Sir, you are under attack!");
    }
}
function useItem(x, y, z, itemId, blockId, side, itemDamage, blockDamage) {
    if (itemId==280) {
        clientMessage("You touched a block with a stick");
    }
}