// Date: 11/22/2016 7:23:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.jtrent238.epicproportions.addons.christmas.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelChristmasTree extends ModelBase
{
  //fields
    ModelRenderer TreeBase;
    ModelRenderer TreePart1;
    ModelRenderer TreePart2;
    ModelRenderer TreePart3;
    ModelRenderer TreePart4;
    ModelRenderer TreePart5;
    ModelRenderer TreePart6;
    ModelRenderer TreePart7;
  
  public ModelChristmasTree()
  {
    textureWidth = 256;
    textureHeight = 32;
    
      TreeBase = new ModelRenderer(this, 0, 0);
      TreeBase.addBox(0F, 0F, 0F, 5, 5, 5);
      TreeBase.setRotationPoint(-2F, 19F, -2F);
      TreeBase.setTextureSize(256, 32);
      TreeBase.mirror = true;
      setRotation(TreeBase, 0F, 0F, 0F);
      TreePart1 = new ModelRenderer(this, 200, 0);
      TreePart1.addBox(0F, 0F, 0F, 13, 4, 13);
      TreePart1.setRotationPoint(-6F, 15F, -6F);
      TreePart1.setTextureSize(256, 32);
      TreePart1.mirror = true;
      setRotation(TreePart1, 0F, 0F, 0F);
      TreePart2 = new ModelRenderer(this, 42, 14);
      TreePart2.addBox(0F, 0F, 0F, 11, 4, 11);
      TreePart2.setRotationPoint(-5F, 11F, -5F);
      TreePart2.setTextureSize(256, 32);
      TreePart2.mirror = true;
      setRotation(TreePart2, 0F, 0F, 0F);
      TreePart3 = new ModelRenderer(this, 0, 14);
      TreePart3.addBox(0F, 0F, 0F, 9, 4, 9);
      TreePart3.setRotationPoint(-4F, 7F, -4F);
      TreePart3.setTextureSize(256, 32);
      TreePart3.mirror = true;
      setRotation(TreePart3, 0F, 0F, 0F);
      TreePart4 = new ModelRenderer(this, 150, 0);
      TreePart4.addBox(0F, 0F, 0F, 7, 4, 7);
      TreePart4.setRotationPoint(-3F, 3F, -3F);
      TreePart4.setTextureSize(256, 32);
      TreePart4.mirror = true;
      setRotation(TreePart4, 0F, 0F, 0F);
      TreePart5 = new ModelRenderer(this, 120, 0);
      TreePart5.addBox(0F, 0F, 0F, 5, 4, 5);
      TreePart5.setRotationPoint(-2F, 0F, -2F);
      TreePart5.setTextureSize(256, 32);
      TreePart5.mirror = true;
      setRotation(TreePart5, 0F, 0F, 0F);
      TreePart6 = new ModelRenderer(this, 25, 0);
      TreePart6.addBox(0F, 0F, 0F, 3, 2, 3);
      TreePart6.setRotationPoint(-1F, -2F, -1F);
      TreePart6.setTextureSize(256, 32);
      TreePart6.mirror = true;
      setRotation(TreePart6, 0F, 0F, 0F);
      TreePart7 = new ModelRenderer(this, 100, 0);
      TreePart7.addBox(0F, 0F, 0F, 1, 1, 1);
      TreePart7.setRotationPoint(0F, -3F, 0F);
      TreePart7.setTextureSize(256, 32);
      TreePart7.mirror = true;
      setRotation(TreePart7, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, Entity f6)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, f6);
    TreeBase.render(f5);
    TreePart1.render(f5);
    TreePart2.render(f5);
    TreePart3.render(f5);
    TreePart4.render(f5);
    TreePart5.render(f5);
    TreePart6.render(f5);
    TreePart7.render(f5);
  }
  
  public void renderModel(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    TreeBase.render(f5);
    TreePart1.render(f5);
    TreePart2.render(f5);
    TreePart3.render(f5);
    TreePart4.render(f5);
    TreePart5.render(f5);
    TreePart6.render(f5);
    TreePart7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
