// Date: 11/9/2016 7:35:11 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.jtrent238.epicproportions.addons.christmas.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelChristmasPresents extends ModelBase
{
  //fields
    ModelRenderer PresentSmall;
    ModelRenderer PresentMed;
    ModelRenderer PresentLarge;
  
  public ModelChristmasPresents()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      PresentSmall = new ModelRenderer(this, 0, 0);
      PresentSmall.addBox(0F, 0F, 0F, 4, 4, 4);
      PresentSmall.setRotationPoint(4F, 20F, 2F);
      PresentSmall.setTextureSize(64, 32);
      PresentSmall.mirror = true;
      setRotation(PresentSmall, 0F, -0.5576792F, 0F);
      PresentMed = new ModelRenderer(this, 0, 10);
      PresentMed.addBox(0F, 0F, 0F, 6, 6, 6);
      PresentMed.setRotationPoint(2F, 18F, 1F);
      PresentMed.setTextureSize(64, 32);
      PresentMed.mirror = true;
      setRotation(PresentMed, 0F, 2.044824F, 0F);
      PresentLarge = new ModelRenderer(this, 27, 10);
      PresentLarge.addBox(0F, 0F, 0F, 6, 6, 6);
      PresentLarge.setRotationPoint(-2F, 18F, 5F);
      PresentLarge.setTextureSize(64, 32);
      PresentLarge.mirror = true;
      setRotation(PresentLarge, 0F, 2.786124F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    PresentSmall.render(f5);
    PresentMed.render(f5);
    PresentLarge.render(f5);
  }
  
  public void renderModel(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    PresentSmall.render(f5);
    PresentMed.render(f5);
    PresentLarge.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
