// Date: 12/5/2016 6:48:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.jtrent238.epicproportions.addons.christmas.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGingerBreadMan extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Head;
    ModelRenderer Arm1;
    ModelRenderer Arm2;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Drop1;
    ModelRenderer Drop2;
    ModelRenderer Drop3;
  
  public ModelGingerBreadMan()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 5, 9, 1);
      Body.setRotationPoint(-2F, 10F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 16, 0);
      Head.addBox(0F, 0F, 0F, 3, 3, 3);
      Head.setRotationPoint(-1F, 7F, -1F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Arm1 = new ModelRenderer(this, 0, 13);
      Arm1.addBox(0F, 0F, 0F, 1, 5, 1);
      Arm1.setRotationPoint(-3F, 11F, 0F);
      Arm1.setTextureSize(64, 32);
      Arm1.mirror = true;
      setRotation(Arm1, 0F, 0F, 0.1745329F);
      Arm2 = new ModelRenderer(this, 6, 13);
      Arm2.addBox(0F, 0F, 0F, 1, 5, 1);
      Arm2.setRotationPoint(3F, 11F, 0F);
      Arm2.setTextureSize(64, 32);
      Arm2.mirror = true;
      setRotation(Arm2, 0F, 0F, -0.1745329F);
      Leg1 = new ModelRenderer(this, 0, 20);
      Leg1.addBox(0F, 0F, 0F, 1, 5, 1);
      Leg1.setRotationPoint(-1F, 19F, 0F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 6, 20);
      Leg2.addBox(0F, 0F, 0F, 1, 5, 1);
      Leg2.setRotationPoint(1F, 19F, 0F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Drop1 = new ModelRenderer(this, 16, 8);
      Drop1.addBox(0F, 0F, 0F, 1, 1, 1);
      Drop1.setRotationPoint(0F, 12F, -0.5F);
      Drop1.setTextureSize(64, 32);
      Drop1.mirror = true;
      setRotation(Drop1, 0F, 0F, 0F);
      Drop2 = new ModelRenderer(this, 16, 11);
      Drop2.addBox(0F, 0F, 0F, 1, 1, 1);
      Drop2.setRotationPoint(0F, 14F, -0.5F);
      Drop2.setTextureSize(64, 32);
      Drop2.mirror = true;
      setRotation(Drop2, 0F, 0F, 0F);
      Drop3 = new ModelRenderer(this, 16, 14);
      Drop3.addBox(0F, 0F, 0F, 1, 1, 1);
      Drop3.setRotationPoint(0F, 16F, -0.5F);
      Drop3.setTextureSize(64, 32);
      Drop3.mirror = true;
      setRotation(Drop3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Head.render(f5);
    Arm1.render(f5);
    Arm2.render(f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Drop1.render(f5);
    Drop2.render(f5);
    Drop3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
