// Date: 7/10/2016 4:30:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.jtrent238.epicproportions.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFred2_0 extends ModelBase
{
  //fields
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer MiddleLongBottom;
    ModelRenderer MiddleTall;
    ModelRenderer MiddleLongTop;
    ModelRenderer Arm1;
    ModelRenderer Arm2;
    ModelRenderer Head;
  
  public ModelFred2_0()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(0F, 0F, 0F, 2, 16, 2);
      Leg1.setRotationPoint(-7F, 8F, 0F);
      Leg1.setTextureSize(64, 32);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(0F, 0F, 0F, 2, 16, 2);
      Leg2.setRotationPoint(5F, 8F, 0F);
      Leg2.setTextureSize(64, 32);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      MiddleLongBottom = new ModelRenderer(this, 0, 0);
      MiddleLongBottom.addBox(0F, 0F, 0F, 20, 3, 2);
      MiddleLongBottom.setRotationPoint(-10F, 6F, 0F);
      MiddleLongBottom.setTextureSize(64, 32);
      MiddleLongBottom.mirror = true;
      setRotation(MiddleLongBottom, 0F, 0F, 0F);
      MiddleTall = new ModelRenderer(this, 0, 0);
      MiddleTall.addBox(0F, 0F, 0F, 2, 23, 2);
      MiddleTall.setRotationPoint(-1F, -11F, 0F);
      MiddleTall.setTextureSize(64, 32);
      MiddleTall.mirror = true;
      setRotation(MiddleTall, 0F, 0F, 0F);
      MiddleLongTop = new ModelRenderer(this, 0, 0);
      MiddleLongTop.addBox(0F, 0F, 0F, 20, 3, 2);
      MiddleLongTop.setRotationPoint(-10F, -5F, 0F);
      MiddleLongTop.setTextureSize(64, 32);
      MiddleLongTop.mirror = true;
      setRotation(MiddleLongTop, 0F, 0F, 0F);
      Arm1 = new ModelRenderer(this, 0, 0);
      Arm1.addBox(0F, 0F, 0F, 2, 11, 2);
      Arm1.setRotationPoint(-11F, -9F, 0F);
      Arm1.setTextureSize(64, 32);
      Arm1.mirror = true;
      setRotation(Arm1, 0F, 0F, 0F);
      Arm2 = new ModelRenderer(this, 0, 0);
      Arm2.addBox(0F, 0F, 0F, 2, 11, 2);
      Arm2.setRotationPoint(9F, -9F, 0F);
      Arm2.setTextureSize(64, 32);
      Arm2.mirror = true;
      setRotation(Arm2, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 8, 8, 8);
      Head.setRotationPoint(-4F, -15F, -3F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Leg1.render(f5);
    Leg2.render(f5);
    MiddleLongBottom.render(f5);
    MiddleTall.render(f5);
    MiddleLongTop.render(f5);
    Arm1.render(f5);
    Arm2.render(f5);
    Head.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
