// Date: 7/31/2016 9:56:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.jtrent238.epicproportions.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCloak extends ModelBase
{
  //fields
    ModelRenderer cloak;
  
  public ModelCloak()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      cloak = new ModelRenderer(this, 0, 0);
      cloak.addBox(0F, 0F, 0F, 10, 22, 1);
      cloak.setRotationPoint(-5F, 0F, 0F);
      cloak.setTextureSize(64, 32);
      cloak.mirror = true;
      setRotation(cloak, 0.2230717F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    cloak.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
