// Date: 7/30/2016 5:56:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.jtrent238.epicproportions.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBlockling_Small extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Arm1;
    ModelRenderer Arm2;
  
  public ModelBlockling_Small()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 23F, 0F, 14, 12, 13);
      Body.setRotationPoint(-7F, -11F, -6F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      //Arm1.mirror = true;
      Arm1 = new ModelRenderer(this, 0, 0);
      Arm1.addBox(-7F, 0F, 0F, 8, 1, 1);
      Arm1.setRotationPoint(-7F, 15F, 0F);
      Arm1.setTextureSize(64, 32);
      Arm1.mirror = true;
      setRotation(Arm1, 0F, 0F, -1.122174F);
      //Arm1.mirror = false;
      Arm2 = new ModelRenderer(this, 0, 0);
      Arm2.addBox(0F, 0F, 0F, 8, 1, 1);
      Arm2.setRotationPoint(7F, 14F, 0F);
      Arm2.setTextureSize(64, 32);
      Arm2.mirror = true;
      setRotation(Arm2, 0F, 0F, 1.145721F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Arm1.render(f5);
    Arm2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
